import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full bg-[#080910] h-full content-center ">
        <section className="">
          <div className="flex items-center place-content-center p-5">
            <div className="">
              <h1 className="text-6xl mt-10 py-2 text-emerald-500 font-bold ">
                Toolkit 🛠
              </h1>
            </div>
          </div>
          <div className="flex items-center place-content-center p-5">
            <div className=" w-3/5 ">
              <p className=" pb-12 text-gray-500 text-center">
                Explore our comprehensive list of awesome web tools for your
                day-to-day programming. Explore our comprehensive list of
                awesome web tools for your day-to-day programming Explore our
                comprehensive list of awesome web tools for your day-to-day
                programming
              </p>
            </div>
          </div>
        </section>
        <section className="  bg-[#121520] h-auto">
          <div className="tags w-3/5 py-20 mx-auto grid grid-cols-6 gap-2 items-center place-content-center">
            <div className="tag">💸 React</div>
            <div className="tag">✨ Frontend</div>
            <div className="tag">🖌 Design</div>
            <div className="tag">🎨 UI/UX</div>
            <div className="tag">✒ Icons</div>
            <div className="tag">📑 Cheatsheets</div>
          </div>
          <div className=" w-4/5 py-10 my-0 mx-auto toolsWrapper grid grid-cols-4 gap-5 items-center place-content-center">
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
            <button className="btn-primary"> Hello </button>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
